site_name: MaoriLoanWords
theme: mkdocs 
repo_url: https://github.com/felipebravom/AffectiveTweets
site_description: Moari LoanWords
nav:
    - Home: index.md
    - Word Vectors: word_vectors.md
    - The Corpus: corpus.md

