site_name: MaoriLoanWords
theme: mkdocs 
repo_url: https://github.com/Waikato/MaoriLoanWords
site_description: Moari LoanWords
nav:
    - Home: index.md
    - The Corpus: corpus.md
    - Word Vectors: word_vectors.md
    - Who we are: team.md
