site_name: Kiwi Words
theme: mkdocs 
repo_url: https://github.com/Waikato/kiwiwords
google_analytics: ['UA-139965982-2', 'mkdocs.org']
site_description: Kiwi Words
nav:
    - Home: index.md
    - The MLT Corpus: corpus.md
    - The HH Sub-Corpus : hh_corpus.md
    - Word Vectors: word_vectors.md
    - Who we are: team.md
