site_name: Kiwi Words
theme: mkdocs 
repo_url: https://github.com/Waikato/kiwiwords
site_description: Kiwi Words
nav:
    - Home: index.md
    - The Corpus: corpus.md
    - Word Vectors: word_vectors.md
    - Who we are: team.md
