site_name: Kiwi Words
theme: mkdocs 
repo_url: https://github.com/Waikato/kiwiwords
google_analytics: ['UA-139965982-2', 'mkdocs.org']
site_description: Kiwi Words
nav:
    - Home: index.md
    - MLT Corpus: corpus.md
    - HH Sub-Corpus : hh_corpus.md
    - Word Embeddings: word_vectors.md
    - Team: team.md
